---
name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Node: setup"
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: "Markdown lint: setup"
        run: npm i -g markdownlint-cli@0.42.0

      - name: "Markdown lint: run"
        run: markdownlint "**/*.md" --ignore node_modules
